const WaitOrders=resolve=>{
    require.ensure(['@/pages/orders/wait-orders'],()=>{
        resolve(require('@/pages/orders/wait-orders'));
    })
}
const WaitPayDetail=resolve=>{
    require.ensure(['@/pages/orders/wait-pay-detail'],()=>{
        resolve(require('@/pages/orders/wait-pay-detail'));
    })
}
const WaitSendDetail=resolve=>{
    require.ensure(['@/pages/orders/wait-send-detail'],()=>{
        resolve(require('@/pages/orders/wait-send-detail'));
    })
}
const OrderList=resolve=>{
    require.ensure(['@/pages/orders/order-list'],()=>{
        resolve(require('@/pages/orders/order-list'));
    })
}
const SaleAfter=resolve=>{
    require.ensure(['@/pages/orders/sale-after'],()=>{
        resolve(require('@/pages/orders/sale-after'));
    })
}
const ChangeOrder=resolve=>{
    require.ensure(['@/pages/orders/change-order'],()=>{
        resolve(require('@/pages/orders/change-order'));
    })
}
const CancelOrder=resolve=>{
    require.ensure(['@/pages/orders/cancel-order'],()=>{
        resolve(require('@/pages/orders/cancel-order'));
    })
}
const CloseOrder=resolve=>{
    require.ensure(['@/pages/orders/close-order'],()=>{
        resolve(require('@/pages/orders/close-order'));
    })
}
const AskRefunds=resolve=>{
    require.ensure(['@/pages/orders/ask-refunds'],()=>{
        resolve(require('@/pages/orders/ask-refunds'));
    })
}
const Refunds=resolve=>{
    require.ensure(['@/pages/orders/refunds'],()=>{
        resolve(require('@/pages/orders/refunds'));
    })
}
const RefundsBack=resolve=>{
    require.ensure(['@/pages/orders/refunds'],()=>{
        resolve(require('@/pages/orders/refunds-back'));
    })
}
const AskRefundsBack=resolve=>{
    require.ensure(['@/pages/orders/ask-refunds-back'],()=>{
        resolve(require('@/pages/orders/ask-refunds-back'));
    })
}
const AskSaleAfter=resolve=>{
    require.ensure(['@/pages/orders/ask-sale-after'],()=>{
        resolve(require('@/pages/orders/ask-sale-after'));
    })
}
const LogisticsInfo=resolve=>{
    require.ensure(['@/pages/orders/logistics-info'],()=>{
        resolve(require('@/pages/orders/logistics-info'));
    })
}
const ChangeGoodsDetail=resolve=>{
    require.ensure(['@/pages/orders/change-goods-detail'],()=>{
        resolve(require('@/pages/orders/change-goods-detail'));
    })
}
const AskChangeGoods=resolve=>{
    require.ensure(['@/pages/orders/ask-change-goods'],()=>{
        resolve(require('@/pages/orders/ask-change-goods'));
    })
}
const SelectChangeGoods=resolve=>{
    require.ensure(['@/pages/orders/select-change-goods'],()=>{
        resolve(require('@/pages/orders/select-change-goods'));
    })
}
const ordersRoutes=[
    {
        path:'/wait-orders/:status',
        name:'wait-orders',
        component:WaitOrders,
        meta:{
            title:'我的订单'
        },
    },
    {
        path:'/wait-pay-detail/:id',
        name:'wait-pay-detail',
        component:WaitPayDetail,
        meta:{
            title:'订单详情'
        },
    },
    {
        path:'/sale-after',
        name:'sale-after',
        component:SaleAfter,
        meta:{
            title:'我的订单'
        },
    },
    {
        path:'/order-list',
        name:'order-list',
        component:OrderList,
        meta:{
            title:'我的订单'
        },
    },
    {
        path:'/change-order/:id',
        name:'change-order',
        component:ChangeOrder,
        meta:{
            title:'申请修改订单',
            keepAlive:true
        },
    },
    {
        path:'/wait-send-detail/:id',
        name:'wait-send-detail',
        component:WaitSendDetail,
        meta:{
            title:'订单详情'
        },
    },
    {
        path:'/cancel-order/:id',
        name:'cancel-order',
        component:CancelOrder,
        meta:{
            title:'取消订单'
        },
    },
    {
        path:'/close-order/:id',
        name:'close-order',
        component:CloseOrder,
        meta:{
            title:'订单详情'
        },
    },
    {
        path:'/ask-refunds/:id',
        name:'ask-refunds',
        component:AskRefunds,
        meta:{
            title:'申请退款'
        },
    },
    {
        path:'/refunds/:id',
        name:'refunds',
        component:Refunds,
        meta:{
            title:'退款详情'
        },
    },
    {
        path:'/refunds-back/:id',
        name:'refunds-back',
        component:RefundsBack,
        meta:{
            title:'退货退款详情'
        },
    },
    {
        path:'/ask-refunds-back/:id',
        name:'ask-refunds-back',
        component:AskRefundsBack,
        meta:{
            title:'申请退货退款'
        },
    },
    {
        path:'/ask-sale-after/:id',
        name:'ask-sale-after',
        component:AskSaleAfter,
        meta:{
            title:'申请售后'
        },
    },
    {
        path:'/logistics-info/:id/:frm',
        name:'logistics-info',
        component:LogisticsInfo,
        meta:{
            title:'填写物流信息'
        },
    },
    {
        path:'/change-goods-detail/:id',
        name:'change-goods-detail',
        component:ChangeGoodsDetail,
        meta:{
            title:'售后包换详情'
        },
    },
    {
        path:'/ask-change-goods/:id',
        name:'ask-change-goods',
        component:AskChangeGoods,
        meta:{
            title:'申请换货'
        },
    },
    {
        path:'/select-change-goods/:id',
        name:'select-change-goods',
        component:SelectChangeGoods,
        meta:{
            title:'选择换货商品'
        },
    },
]
export default ordersRoutes;